# SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


[tool.isort]
profile = "black"
line_length = 100
known_first_party = "holoscan"
skip_glob = ["build*/*", "install*/*", ".cache/*"]
# make sure we don't change the import order in top-level Python __init__.py
skip = ["./python/pybind11/__init__.py"]

[tool.black]
line-length = 100
target-version = ['py37']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^.cache/*    # exclude .cache folder
  | ^build*/*  # exclude build folders
  | ^install*/*  # exclude install folders
)
'''

[tool.codespell]
skip = "_deps,build*,.cache,html,_build,_static,generated,latex,install*,.git,xml,vale"
ignore-words-list = "bu,dne,unexpect"
